"""add status to curriculum_documents

Revision ID: 5f8613dc7ef8
Revises: 62e6e3c0b1b1
Create Date: 2026-09-16 08:54:04.323789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8613dc7ef8'
down_revision: Union[str, Sequence[str], None] = '62e6e3c0b1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum_documents', sa.Column('status', sa.String(), server_default='processing', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculum_documents', 'status')
    # ### end Alembic commands ###
