import asyncio
from uuid import UUID
from celery.utils.log import get_task_logger

from app.tasks.celery_app import celery_app
from app.db.session import AsyncSessionLocal
from app.db.repositories.lesson_plan_repository import lesson_plan_repo
from app.core.services.rag_service import rag_service
from app.core.services.llm_service import llm_service

logger = get_task_logger(__name__)

async def _run_generation(lesson_plan_id: str, user_id: str) -> None:
    """Async core of the generation task."""
    async with AsyncSessionLocal() as db:
        try:
            # 1. Fetch the pending lesson plan
            plan = await lesson_plan_repo.get(db, lesson_plan_id)
            if not plan:
                logger.error(f"Lesson plan {lesson_plan_id} not found.")
                return

            # 2. Retrieve context via RAG (pre-filtered by grade and subject)
            context_chunks = await rag_service.retrieve_context(
                db=db,
                topic=plan.topic,
                grade_level=plan.grade_level,
                subject=plan.subject,
                user_id=UUID(user_id)
            )

            # 3. Generate structured lesson plan via Gemini
            generated_content = await llm_service.generate_lesson_plan(
                db=db,
                context_chunks=context_chunks,
                grade_level=plan.grade_level,
                subject=plan.subject,
                topic=plan.topic,
                user_id=UUID(user_id),
                lesson_plan_id=UUID(lesson_plan_id)
            )

            # 4. Update the lesson plan status
            if "error" in generated_content:
                plan.status = "failed"
                plan.generated_content = generated_content
                logger.error(f"LLM Generation failed for {lesson_plan_id}: {generated_content}")
            else:
                plan.status = "completed"
                plan.generated_content = generated_content

            # Commit the transaction (this commits the cost logs generated by the services too)
            await db.commit()
            logger.info(f"Successfully generated lesson plan {lesson_plan_id}")

        except Exception as e:
            logger.exception(f"Fatal error generating lesson plan {lesson_plan_id}: {e}")
            await db.rollback()
            
            # Use a fresh transaction to ensure we mark the plan as failed
            async with AsyncSessionLocal() as fallback_db:
                failed_plan = await lesson_plan_repo.get(fallback_db, lesson_plan_id)
                if failed_plan:
                    failed_plan.status = "failed"
                    await fallback_db.commit()
            raise e

@celery_app.task(bind=True, name="tasks.generate_lesson_plan")
def generate_lesson_plan_task(self, lesson_plan_id: str, user_id: str):
    """
    Synchronous Celery task wrapper that executes the async RAG and LLM pipeline.
    """
    logger.info(f"Starting generation task for plan {lesson_plan_id}")
    asyncio.run(_run_generation(lesson_plan_id, user_id))
